In [1]:
import pandas as pd
import numpy as np
import os
import datetime
from dateutil.parser import parse

In [3]:
os.chdir('E:\\Christ\\2021\\Dataset')

### Step1: Read data from second sheet

In [4]:
bank1 = pd.read_excel('BANKS2020.xlsx')

In [5]:
bank1.head()

Empty DataFrame
Columns: []
Index: []

In [6]:
bank1 = pd.read_excel('BANKS2020.xlsx', sheet_name=1)

In [7]:
bank1.head()

,ICICI Bank,Previous Years »,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Standalone Balance Sheet,------------------- in Rs. Cr. ---------------...,NaN,NaN,NaN,NaN
1,NaN,Mar 21,2020,2019,2018,2017
2,EQUITIES AND LIABILITIES,NaN,NaN,NaN,NaN,NaN
3,SHAREHOLDER'S FUNDS,NaN,NaN,NaN,NaN,NaN
4,Equity Share Capital,1386.51,1294.76,1294.76,1289.46,1294.14

### Step-2:Transpose the dataset

In [21]:
bank1[1:].T

,1,2,3,4,5,6,7,8,9,10,...,81,82,83,84,85,86,87,88,89,90
ICICI Bank,NaN,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Previous Years »,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,932522,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,770969,...,12.28,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,770969,...,5.23,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,652920,...,10.56,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 5,2017,NaN,NaN,1294.14,1294.14,0,107074,107074,108368,652920,...,16.84,16.77,NaN,125,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
bank_t = bank1[1:]

In [17]:
bank_t.head()

,ICICI Bank,Previous Years »,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
1,NaN,Mar 21,2020,2019,2018,2017
2,EQUITIES AND LIABILITIES,NaN,NaN,NaN,NaN,NaN
3,SHAREHOLDER'S FUNDS,NaN,NaN,NaN,NaN,NaN
4,Equity Share Capital,1386.51,1294.76,1294.76,1289.46,1294.14
5,Total Share Capital,1386.51,1294.76,1298.25,1289.46,1294.14

In [18]:
bank_t = bank1.T

In [19]:
bank_t.head()

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
ICICI Bank,Standalone Balance Sheet,NaN,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Previous Years »,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,12.28,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,5.23,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,10.56,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
bank_t.head()

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
ICICI Bank,Standalone Balance Sheet,NaN,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Previous Years »,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,12.28,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,5.23,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,10.56,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN

### Step-3: Remove columns with nan

In [14]:
bank_t.dropna(how='all', axis=1, inplace=True)

In [15]:
bank_t.head()

,0,1,2,3,4,5,6,7,8,9,...,76,77,78,79,80,81,82,83,84,90
ICICI Bank,Standalone Balance Sheet,NaN,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,OTHER INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),Source : Dion Global Solutions Limited
Previous Years »,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,0,0,0,NaN,NaN,24.01,23.67,NaN,0,NaN
Unnamed: 2,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,0,21327.5,25810.4,NaN,NaN,12.28,12.08,NaN,0,NaN
Unnamed: 3,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,0,17879.6,21858.6,NaN,NaN,5.23,5.17,NaN,50,NaN
Unnamed: 4,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,8.73,18495.3,25522.4,NaN,NaN,10.56,10.46,NaN,75,NaN

### Step-4: Convert the first value (nan) in the first column to year

In [24]:
bank_t[1][0]

nan

In [25]:
bank_t[1][0] = 'year'

In [26]:
bank_t.head()

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
ICICI Bank,Standalone Balance Sheet,year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Previous Years »,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,12.28,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,5.23,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,10.56,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
bank_t.columns

RangeIndex(start=0, stop=91, step=1)

### Step-5: Copy the data file and rename it and store the first index value i.e, bank name

In [31]:
bank_t.index[0]

'ICICI Bank'

In [32]:
bank_t1 = bank_t.copy()

In [28]:
bank_t.iloc[0]

0                  Standalone Balance Sheet
1                                       year
2                   EQUITIES AND LIABILITIES
3                        SHAREHOLDER'S FUNDS
4                       Equity Share Capital
                       ...
86                                       NaN
87                                       NaN
88                                       NaN
89                                       NaN
90    Source : Dion Global Solutions Limited
Name: ICICI Bank, Length: 91, dtype: object

### Step-6: Convert the first row into column names

In [34]:
bank_t1.columns = bank_t.iloc[0]

In [35]:
bank_t1.head()

ICICI Bank,Standalone Balance Sheet,year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
ICICI Bank,Standalone Balance Sheet,year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Previous Years »,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,12.28,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,5.23,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,10.56,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN

### Step-7: Remove the first row

In [36]:
bank_t1[1:]

ICICI Bank,Standalone Balance Sheet,year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Previous Years »,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 2,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,12.28,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 3,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,5.23,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 4,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,10.56,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 5,NaN,2017,NaN,NaN,1294.14,1294.14,0,107074,107074,108368,...,16.84,16.77,NaN,125,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
bank_t1 = bank_t1[1:]

In [40]:
bank_t.index[0]

'ICICI Bank'

### Step-8: Create a variable called Symbol with respective bank name

In [41]:
bank_t1['Symbol'] = bank_t.index[0]

In [42]:
bank_t1.head()

ICICI Bank,Standalone Balance Sheet,year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited,Symbol
Previous Years »,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,ICICI Bank
Unnamed: 2,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,ICICI Bank
Unnamed: 3,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN,ICICI Bank
Unnamed: 4,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN,ICICI Bank
Unnamed: 5,NaN,2017,NaN,NaN,1294.14,1294.14,0,107074,107074,108368,...,16.77,NaN,125,NaN,NaN,NaN,NaN,NaN,NaN,ICICI Bank

### Step-9: Set the index with bank symbol

In [43]:
bank_t1.set_index('Symbol', inplace=True)

In [44]:
bank_t1.head()

ICICI Bank,Standalone Balance Sheet,year,EQUITIES AND LIABILITIES,SHAREHOLDER'S FUNDS,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,...,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND PERCENTAGE,Equity Dividend Rate (%),NaN,NaN,NaN,NaN,NaN,Source : Dion Global Solutions Limited
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,------------------- in Rs. Cr. ---------------...,Mar 21,NaN,NaN,1386.51,1386.51,0,146123,146123,147509,...,24.01,23.67,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,NaN,2020,NaN,NaN,1294.76,1294.76,3114.87,112091,115206,116504,...,12.28,12.08,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,NaN,2019,NaN,NaN,1294.76,1298.25,0,115206,115206,116508,...,5.23,5.17,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,NaN,2018,NaN,NaN,1289.46,1289.46,3044.51,104029,107074,108368,...,10.56,10.46,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN
ICICI Bank,NaN,2017,NaN,NaN,1294.14,1294.14,0,107074,107074,108368,...,16.84,16.77,NaN,125,NaN,NaN,NaN,NaN,NaN,NaN

### Step-10: Remove the rows and columns will all nan

In [45]:
bank_t1.dropna(how='all', axis=1, inplace=True)

In [46]:
bank_t1.head()

ICICI Bank,Standalone Balance Sheet,year,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,...,Transfer To / From Investment Reserve,Transfer To / From Revenue And Other Reserves,Dividend and Dividend Tax for The Previous Year,Equity Share Dividend,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,Basic EPS (Rs.),Diluted EPS (Rs.),Equity Dividend Rate (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,------------------- in Rs. Cr. ---------------...,Mar 21,1386.51,1386.51,0,146123,146123,147509,932522,91631,...,0,0,0,0,0,0,0,24.01,23.67,0
ICICI Bank,NaN,2020,1294.76,1294.76,3114.87,112091,115206,116504,770969,162897,...,669,0,645.31,0,0,21327.5,25810.4,12.28,12.08,0
ICICI Bank,NaN,2019,1294.76,1298.25,0,115206,115206,116508,770969,162897,...,1269.2,350,0,965.13,0,17879.6,21858.6,5.23,5.17,50
ICICI Bank,NaN,2018,1289.46,1289.46,3044.51,104029,107074,108368,652920,165320,...,0,700,0,1457.46,8.73,18495.3,25522.4,10.56,10.46,75
ICICI Bank,NaN,2017,1294.14,1294.14,0,107074,107074,108368,652920,165320,...,0,0,-6.24,0,0,18744.9,26933.3,16.84,16.77,125

In [47]:
bank_t1.shape

(5, 68)

In [48]:
bank_t1.dropna(how='all', axis=0, inplace=True)

In [49]:
bank_t1.shape

(5, 68)

In [50]:
list(bank_t1)

['Standalone Balance Sheet\xa0',
 'year',
 'Equity Share Capital',
 'Total Share Capital',
 'Revaluation Reserve',
 'Reserves and Surplus',
 'Total Reserves and Surplus',
 'Total ShareHolders Funds',
 'Deposits',
 'Borrowings',
 'Other Liabilities and Provisions',
 'Total Capital and Liabilities',
 'Cash and Balances with Reserve Bank of India',
 'Balances with Banks Money at Call and Short Notice',
 'Investments',
 'Advances',
 'Fixed Assets',
 'Other Assets',
 'Total Assets',
 'Number of Branches',
 'Number of Employees',
 'Capital Adequacy Ratios (%)',
 'Tier 1 (%)',
 'Tier 2 (%)',
 'Gross NPA',
 'Gross NPA (%)',
 'Net NPA',
 'Net NPA (%)',
 'Net NPA To Advances (%)',
 'Bills for Collection',
 'Contingent Liabilities',
 'ICICI Bank',
 'Standalone Profit & Loss account\xa0',
 nan,
 nan,
 'Interest / Discount on Advances / Bills',
 'Income from Investments',
 'Interest on Balance with RBI and Other Inter-Bank funds',
 'Others',
 'Total Interest Earned',
 'Other Income',
 'Total Income',
 'Interest Expended',
 'Payments to and Provisions for Employees',
 'Depreciation',
 'Operating Expenses (excludes Employee Cost & Depreciation)',
 'Total Operating Expenses',
 'Provision Towards Income Tax',
 'Provision Towards Deferred Tax',
 'Other Provisions and Contingencies',
 'Total Provisions and Contingencies',
 'Total Expenditure',
 'Net Profit / Loss for The Year',
 'Net Profit / Loss After EI & Prior Year Items',
 'Profit / Loss Brought Forward',
 'Total Profit / Loss available for Appropriations',
 'Transfer To / From Statutory Reserve',
 'Transfer To / From Capital Reserve',
 'Transfer To / From Investment Reserve',
 'Transfer To / From Revenue And Other Reserves',
 'Dividend and Dividend Tax for The Previous Year',
 'Equity Share Dividend',
 'Tax On Dividend',
 'Balance Carried Over To Balance Sheet',
 'Total Appropriations',
 'Basic EPS (Rs.)',
 'Diluted EPS (Rs.)',
 'Equity Dividend Rate (%)']

### Step-11: Remove the columns named as nan

In [51]:
bank_t1.columns.notnull()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [52]:
bank_t1 = bank_t1.loc[:,bank_t1.columns.notnull()]

In [53]:
list(bank_t1)

['Standalone Balance Sheet\xa0',
 'year',
 'Equity Share Capital',
 'Total Share Capital',
 'Revaluation Reserve',
 'Reserves and Surplus',
 'Total Reserves and Surplus',
 'Total ShareHolders Funds',
 'Deposits',
 'Borrowings',
 'Other Liabilities and Provisions',
 'Total Capital and Liabilities',
 'Cash and Balances with Reserve Bank of India',
 'Balances with Banks Money at Call and Short Notice',
 'Investments',
 'Advances',
 'Fixed Assets',
 'Other Assets',
 'Total Assets',
 'Number of Branches',
 'Number of Employees',
 'Capital Adequacy Ratios (%)',
 'Tier 1 (%)',
 'Tier 2 (%)',
 'Gross NPA',
 'Gross NPA (%)',
 'Net NPA',
 'Net NPA (%)',
 'Net NPA To Advances (%)',
 'Bills for Collection',
 'Contingent Liabilities',
 'ICICI Bank',
 'Standalone Profit & Loss account\xa0',
 'Interest / Discount on Advances / Bills',
 'Income from Investments',
 'Interest on Balance with RBI and Other Inter-Bank funds',
 'Others',
 'Total Interest Earned',
 'Other Income',
 'Total Income',
 'Interest Expended',
 'Payments to and Provisions for Employees',
 'Depreciation',
 'Operating Expenses (excludes Employee Cost & Depreciation)',
 'Total Operating Expenses',
 'Provision Towards Income Tax',
 'Provision Towards Deferred Tax',
 'Other Provisions and Contingencies',
 'Total Provisions and Contingencies',
 'Total Expenditure',
 'Net Profit / Loss for The Year',
 'Net Profit / Loss After EI & Prior Year Items',
 'Profit / Loss Brought Forward',
 'Total Profit / Loss available for Appropriations',
 'Transfer To / From Statutory Reserve',
 'Transfer To / From Capital Reserve',
 'Transfer To / From Investment Reserve',
 'Transfer To / From Revenue And Other Reserves',
 'Dividend and Dividend Tax for The Previous Year',
 'Equity Share Dividend',
 'Tax On Dividend',
 'Balance Carried Over To Balance Sheet',
 'Total Appropriations',
 'Basic EPS (Rs.)',
 'Diluted EPS (Rs.)',
 'Equity Dividend Rate (%)']

In [54]:
bank_t1.shape

(5, 66)

In [55]:
bank_t1.head()

ICICI Bank,Standalone Balance Sheet,year,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,...,Transfer To / From Investment Reserve,Transfer To / From Revenue And Other Reserves,Dividend and Dividend Tax for The Previous Year,Equity Share Dividend,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,Basic EPS (Rs.),Diluted EPS (Rs.),Equity Dividend Rate (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,------------------- in Rs. Cr. ---------------...,Mar 21,1386.51,1386.51,0,146123,146123,147509,932522,91631,...,0,0,0,0,0,0,0,24.01,23.67,0
ICICI Bank,NaN,2020,1294.76,1294.76,3114.87,112091,115206,116504,770969,162897,...,669,0,645.31,0,0,21327.5,25810.4,12.28,12.08,0
ICICI Bank,NaN,2019,1294.76,1298.25,0,115206,115206,116508,770969,162897,...,1269.2,350,0,965.13,0,17879.6,21858.6,5.23,5.17,50
ICICI Bank,NaN,2018,1289.46,1289.46,3044.51,104029,107074,108368,652920,165320,...,0,700,0,1457.46,8.73,18495.3,25522.4,10.56,10.46,75
ICICI Bank,NaN,2017,1294.14,1294.14,0,107074,107074,108368,652920,165320,...,0,0,-6.24,0,0,18744.9,26933.3,16.84,16.77,125

In [58]:
bank1 = pd.read_excel('BANKS2020.xlsx', sheet_name=1)
bank1 = bank1[1:]
bank_t = bank1.T
bank_t.dropna(how='all', axis=1, inplace=True)
bank_t[1][0] = 'year'
bank_t1 = bank_t.copy()
bank_t1.columns = bank_t.iloc[0]
bank_t1 = bank_t1[1:]
bank_t1['Symbol'] = bank_t.index[0]
bank_t1.set_index('Symbol', inplace=True)
bank_t1.dropna(how='all', axis=1, inplace=True)
bank_t1 = bank_t1.loc[:,bank_t1.columns.notnull()]

In [59]:
bank_t1.head()

ICICI Bank,year,Equity Share Capital,Total Share Capital,Revaluation Reserve,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,Other Liabilities and Provisions,...,Transfer To / From Investment Reserve,Transfer To / From Revenue And Other Reserves,Dividend and Dividend Tax for The Previous Year,Equity Share Dividend,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,Basic EPS (Rs.),Diluted EPS (Rs.),Equity Dividend Rate (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,Mar 21,1386.51,1386.51,0,146123,146123,147509,932522,91631,58770.4,...,0,0,0,0,0,0,0,24.01,23.67,0
ICICI Bank,2020,1294.76,1294.76,3114.87,112091,115206,116504,770969,162897,47995,...,669,0,645.31,0,0,21327.5,25810.4,12.28,12.08,0
ICICI Bank,2019,1294.76,1298.25,0,115206,115206,116508,770969,162897,47995,...,1269.2,350,0,965.13,0,17879.6,21858.6,5.23,5.17,50
ICICI Bank,2018,1289.46,1289.46,3044.51,104029,107074,108368,652920,165320,37851.5,...,0,700,0,1457.46,8.73,18495.3,25522.4,10.56,10.46,75
ICICI Bank,2017,1294.14,1294.14,0,107074,107074,108368,652920,165320,37851.5,...,0,0,-6.24,0,0,18744.9,26933.3,16.84,16.77,125

In [61]:
bank_t1.shape

(5, 65)

### Step-12: Import another sheet

In [64]:
bank2 = pd.read_excel('BANKS2020.xlsx', sheet_name=2)
bank2 = bank2[1:]
bank_t = bank2.T
bank_t.dropna(how='all', axis=1, inplace=True)
bank_t[1][0] = 'year'
bank_t2 = bank_t.copy()
bank_t2.columns = bank_t.iloc[0]
bank_t2 = bank_t2[1:]
bank_t2['Symbol'] = bank_t.index[0]
bank_t2.set_index('Symbol', inplace=True)
bank_t2.dropna(how='all', axis=1, inplace=True)
bank_t2 = bank_t2.loc[:,bank_t2.columns.notnull()]

In [65]:
bank_t2.head()

HDFC Bank,year,Equity Share Capital,Total Share Capital,Reserves and Surplus,Total Reserves and Surplus,Total ShareHolders Funds,Deposits,Borrowings,Other Liabilities and Provisions,Total Capital and Liabilities,...,Transfer To / From General Reserve,Transfer To / From Investment Reserve,Dividend and Dividend Tax for The Previous Year,Equity Share Dividend,Tax On Dividend,Balance Carried Over To Balance Sheet,Total Appropriations,Basic EPS (Rs.),Diluted EPS (Rs.),Equity Dividend Rate (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
HDFC Bank,Mar 20,548.33,548.33,170438,170438,170986,1.1475e+06,144629,67394.4,1.53051e+06,...,2625.73,1134,0,6540.31,0,57492.4,75480.6,48.01,47.66,250
HDFC Bank,2020,548.33,548.33,170438,170438,170986,1.1475e+06,144629,67394.4,1.53051e+06,...,2107.82,773,0,4052.59,0,49223.3,61531.6,78.65,77.87,750
HDFC Bank,2019,544.66,544.66,148662,148662,149206,923141,117085,55108.3,1.24454e+06,...,1748.67,-44.2,3390.58,0,0,40453.4,50155.7,67.76,66.84,650
HDFC Bank,2018,544.66,544.66,148662,148662,149206,923141,117085,55108.3,1.24454e+06,...,1454.96,4.29,-1.69,0,0,32668.9,38077.3,57.18,56.43,550
HDFC Bank,2017,519.02,519.02,105776,105776,106295,788771,123105,45763.7,1.06393e+06,...,1229.62,-8.52,-11.71,2401.78,488.95,23527.7,30924,48.84,48.26,475

### Step-13: Concatenate two files

In [66]:
bank_all = pd.concat([bank_t1, bank_t2], axis=0) #Appending the rows

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [67]:
bank_all

,Advances,Balance Carried Over To Balance Sheet,Balances with Banks Money at Call and Short Notice,Basic EPS (Rs.),Bills for Collection,Borrowings,Capital Adequacy Ratios (%),Cash and Balances with Reserve Bank of India,Contingent Liabilities,Deposits,...,Total Provisions and Contingencies,Total Reserves and Surplus,Total Share Capital,Total ShareHolders Funds,Transfer To / From Capital Reserve,Transfer To / From General Reserve,Transfer To / From Investment Reserve,Transfer To / From Revenue And Other Reserves,Transfer To / From Statutory Reserve,year
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,733729,0,87097.1,24.01,0,91631,0.17,46031.2,0,932522,...,20204.5,146123,1386.51,147509,0,NaN,0,0,0,Mar 21
ICICI Bank,645290,21327.5,83871.8,12.28,48216.2,162897,16,35284,2.52383e+06,770969,...,20170.5,115206,1294.76,116504,395.44,NaN,669,0,1982.8,2020
ICICI Bank,645290,17879.6,83871.8,5.23,0,162897,16,35284,0,770969,...,20074.6,115206,1298.25,116508,28,NaN,1269.2,350,840.9,2019
ICICI Bank,586647,18495.3,42438.3,10.56,49392,165320,17,37858,1.92204e+06,652920,...,17964.1,107074,1289.46,108368,2565.46,NaN,0,700,1694.4,2018
ICICI Bank,586647,18744.9,42438.3,16.84,0,165320,17,37858,0,652920,...,16685.7,107074,1294.14,108368,5293.3,NaN,0,0,2450.3,2017
HDFC Bank,993703,57492.4,14413.6,48.01,51584.9,144629,19,72205.1,1.12895e+06,1.1475e+06,...,22492.2,170438,548.33,170986,1123.85,2625.73,1134,NaN,6564.33,Mar 20
HDFC Bank,993703,49223.3,14413.6,78.65,0,144629,19,72205.1,0,1.1475e+06,...,18671.6,170438,548.33,170986,105.34,2107.82,773,NaN,5269.54,2020
HDFC Bank,819401,40453.4,34584,67.76,49952.8,117085,17,46763.6,1.02472e+06,923141,...,15138.1,148662,544.66,149206,235.52,1748.67,-44.2,NaN,4371.68,2019
HDFC Bank,819401,32668.9,34584,57.18,0,117085,17,46763.6,0,923141,...,11182.7,148662,544.66,149206,313.41,1454.96,4.29,NaN,3637.41,2018
HDFC Bank,658333,23527.7,18244.6,48.84,42753.8,123105,15,104670,875488,788771,...,9067.32,105776,519.02,106295,222.15,1229.62,-8.52,NaN,3074.05,2017

In [71]:
bank = pd.DataFrame()

for i in np.arange(1,28):
    df = pd.read_excel('BANKS2020.xlsx', sheet_name=i)
    df = df[1:]
    df = df.T
    df.dropna(how='all', axis=1, inplace=True)
    df.dropna(how='all', axis=0, inplace=True)
    df[1][0] = 'year'
    df1 = df.copy()
    df1.columns = df1.iloc[0]
    df1 = df1[1:]
    df1['Symbol'] = df.index[0]
    df1.set_index('Symbol', inplace=True)
    df1.dropna(how='all', axis=1, inplace=True)
    df1.dropna(how='all', axis=0, inplace=True)
    df1 = df1.loc[:,df1.columns.notnull()]
    bank = pd.concat([bank, df1])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [72]:
bank

,Advances,Axis Bank,Balance Carried Over To Balance Sheet,Balances with Banks Money at Call and Short Notice,Bandhan Bank,Basic EPS (Rs.),Bills for Collection,Borrowings,Capital Adequacy Ratios (%),Cash and Balances with Reserve Bank of India,...,Total ShareHolders Funds,Transfer To / From Capital Reserve,Transfer To / From General Reserve,Transfer To / From Investment Reserve,Transfer To / From Revenue And Other Reserves,Transfer To / From Special Reserve,Transfer To / From Statutory Reserve,Transferred on Amalgamation,Yes Bank,year
Symbol,,,,,,,,,,,,,,,,,,,,,
ICICI Bank,733729,NaN,0,87097.1,NaN,24.01,0,91631,0.17,46031.2,...,147509,0,NaN,0,0,NaN,0,NaN,NaN,Mar 21
ICICI Bank,645290,NaN,21327.5,83871.8,NaN,12.28,48216.2,162897,16,35284,...,116504,395.44,NaN,669,0,NaN,1982.8,NaN,NaN,2020
ICICI Bank,645290,NaN,17879.6,83871.8,NaN,5.23,0,162897,16,35284,...,116508,28,NaN,1269.2,350,NaN,840.9,NaN,NaN,2019
ICICI Bank,586647,NaN,18495.3,42438.3,NaN,10.56,49392,165320,17,37858,...,108368,2565.46,NaN,0,700,NaN,1694.4,NaN,NaN,2018
ICICI Bank,586647,NaN,18744.9,42438.3,NaN,16.84,0,165320,17,37858,...,108368,5293.3,NaN,0,0,NaN,2450.3,NaN,NaN,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Union Bank of India,288761,NaN,0,28424.7,NaN,20.42,18427.1,45680.8,12,21016.5,...,25096.8,44.85,NaN,NaN,548.17,NaN,405.5,NaN,NaN,2017
Bank Of Baroda,690121,NaN,NaN,89255.3,NaN,1.64,0,93069.3,13,32645.8,...,71856.2,210.36,0,-67.3,0,182.08,108.38,NaN,NaN,2020
Bank Of Baroda,468819,NaN,NaN,62567.9,NaN,-10.53,49059.9,67201.3,13,26661.7,...,45941.1,0,0,0,-2431.81,0,0,NaN,NaN,2019
Bank Of Baroda,427432,NaN,NaN,70197.7,NaN,6,45779.7,62572,12,22699.6,...,43394.8,353.65,0,0,0,350.92,345.78,NaN,NaN,2018
Bank Of Baroda,383259,NaN,NaN,127690,NaN,-23.89,37599.4,30611.4,13,22780.2,...,40303.2,0,-5395.54,0,0,0,0,NaN,NaN,2017

In [75]:
bank.index.unique()

Index(['ICICI Bank', 'HDFC Bank', 'Kotak Mahindra Bank', 'Axis Bank',
       'IndusInd Bank', 'Bandhan Bank', 'Yes Bank', 'IDFC First Bank',
       'Federal Bank', 'City Union Bank', 'Equitas Small Finance Bank',
       'Karur Vysya Bank', 'DCB Bank', 'Karnataka Bank', 'South Indian Bank',
       'State Bank of India', 'Punjab National Bank', 'Indian Overseas Bank',
       'Canara Bank', 'Bank Of India', 'Bank of Maharashtra', 'Indian Bank',
       'UCO Bank', 'Central Bank of India', 'Punjab & Sind Bank',
       'Union Bank of India', 'Bank Of Baroda'],
      dtype='object', name='Symbol')

In [76]:
bank.to_csv('bank_clean_data.csv')